
title: Bahram's CV
url: 'http://www.bahrambeigy.ir'
baseurl: '/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Bahram Bahrambeigy
tagline: SysAdmin & Backend Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: bahram@bahrambeigy.ir
#phone: 012 345 6789
website: www.bahrambeigy.ir #do not add http://
linkedin: bahrambeigy
github: bahrambeigy
#twitter: '@webjeda'


# Tracker
#analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
